[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino@^2.3.6
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
  shirriff/IRremote@^4.4.1
